import type { ComponentDefinition } from '~/types/builder'

export const dataComponents: ComponentDefinition[] = [
	{
		type: 'accordion',
		name: 'UAccordion',
		category: 'data',
		icon: 'lucide:chevrons-down-up',
		description: 'A stacked set of interactive collapsible panels',
		isContainer: false,
		defaultProps: {
			items: 'Is Nuxt UI free?:Yes completely free and open source, Can I use with Vue?:Yes works with standalone Vue projects, Is it production-ready?:Used by thousands of apps in production',
			type: 'single',
			collapsible: true,
			trailingIcon: 'lucide:chevron-down',
			disabled: false,
			unmountOnHide: true,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
			margin: 'my-4',
		},
		propsSchema: [
			{
				name: 'items',
				label: 'Items (Label:Content comma separated)',
				type: 'textarea',
				default: 'Is Nuxt UI free?:Yes completely free and open source, Can I use with Vue?:Yes works with standalone Vue projects, Is it production-ready?:Used by thousands of apps in production',
			},
			{
				name: 'type',
				label: 'Selection Mode',
				type: 'select',
				options: ['single', 'multiple'],
				default: 'single',
			},
			{
				name: 'collapsible',
				label: 'Allow Collapsing Active Item',
				type: 'boolean',
				default: true,
			},
			{
				name: 'trailingIcon',
				label: 'Trailing Icon',
				type: 'icon',
				default: 'lucide:chevron-down',
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'carousel',
		name: 'UCarousel',
		category: 'data',
		icon: 'lucide:gallery-horizontal',
		description: 'Interactive multi-slide image / card carousel slider powered by Embla',
		isContainer: false,
		defaultProps: {
			items: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800, https://images.unsplash.com/photo-1558655146-d09347e92766?w=800, https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800',
			arrows: true,
			dots: true,
			orientation: 'horizontal',
			loop: true,
			autoplay: true,
			autoScroll: false,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'items',
				label: 'Image URLs (Comma separated)',
				type: 'textarea',
				default: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800, https://images.unsplash.com/photo-1558655146-d09347e92766?w=800, https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800',
			},
			{
				name: 'arrows',
				label: 'Show Next/Prev Arrows',
				type: 'boolean',
				default: true,
			},
			{
				name: 'dots',
				label: 'Show Pagination Dots',
				type: 'boolean',
				default: true,
			},
			{
				name: 'orientation',
				label: 'Scroll Orientation',
				type: 'select',
				options: ['horizontal', 'vertical'],
				default: 'horizontal',
			},
			{
				name: 'loop',
				label: 'Infinite Loop',
				type: 'boolean',
				default: true,
			},
			{
				name: 'autoplay',
				label: 'Autoplay',
				type: 'boolean',
				default: true,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'empty',
		name: 'UEmpty',
		category: 'data',
		icon: 'lucide:inbox',
		description: 'Placeholder state display when there is no data or content',
		isContainer: false,
		defaultProps: {
			title: 'No projects found',
			description: 'It looks like you haven\'t added any projects. Create one to get started.',
			icon: 'lucide:file-question',
			variant: 'outline',
			size: 'md',
			loading: false,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
			padding: 'p-8',
			margin: 'my-4',
		},
		propsSchema: [
			{
				name: 'title',
				label: 'Empty Title',
				type: 'string',
				default: 'No projects found',
			},
			{
				name: 'description',
				label: 'Description Text',
				type: 'textarea',
				default: 'It looks like you haven\'t added any projects. Create one to get started.',
			},
			{
				name: 'icon',
				label: 'Icon Identifier',
				type: 'icon',
				default: 'lucide:file-question',
			},
			{
				name: 'variant',
				label: 'Variant',
				type: 'select',
				options: ['outline', 'naked', 'solid'],
				default: 'outline',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'loading',
				label: 'Loading State',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'marquee',
		name: 'UMarquee',
		category: 'data',
		icon: 'lucide:play',
		description: 'Continuously scrolling continuous ticker or logo stream',
		isContainer: false,
		defaultProps: {
			items: 'Nuxt, Vue, Tailwind CSS, TypeScript, Vite, Nitro, Bun',
			pauseOnHover: true,
			reverse: false,
			orientation: 'horizontal',
			speed: 20,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
			margin: 'my-4',
		},
		propsSchema: [
			{
				name: 'items',
				label: 'Ticker Items (Comma separated)',
				type: 'textarea',
				default: 'Nuxt, Vue, Tailwind CSS, TypeScript, Vite, Nitro, Bun',
			},
			{
				name: 'pauseOnHover',
				label: 'Pause on Hover',
				type: 'boolean',
				default: true,
			},
			{
				name: 'reverse',
				label: 'Reverse Direction',
				type: 'boolean',
				default: false,
			},
			{
				name: 'orientation',
				label: 'Orientation',
				type: 'select',
				options: ['horizontal', 'vertical'],
				default: 'horizontal',
			},
			{
				name: 'speed',
				label: 'Scroll Speed (seconds)',
				type: 'number',
				default: 20,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'scroll-area',
		name: 'UScrollArea',
		category: 'data',
		icon: 'lucide:arrow-down-up',
		description: 'Custom styled cross-browser scrollable viewport container',
		isContainer: true,
		defaultProps: {
			type: 'auto',
			scrollbars: 'vertical',
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
			height: 'h-48',
			padding: 'p-4',
		},
		propsSchema: [
			{
				name: 'type',
				label: 'Scrollbar Visibility Type',
				type: 'select',
				options: ['auto', 'always', 'scroll', 'hover'],
				default: 'auto',
			},
			{
				name: 'scrollbars',
				label: 'Scrollbars Direction',
				type: 'select',
				options: ['vertical', 'horizontal', 'both'],
				default: 'vertical',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'table',
		name: 'UTable',
		category: 'data',
		icon: 'lucide:table-2',
		description: 'Interactive data table with sort, paginate and row selection',
		isContainer: false,
		defaultProps: {
			caption: 'Users Directory',
			loading: false,
			sticky: false,
			as: 'table',
		},
		defaultStyles: {
			width: 'w-full',
			margin: 'my-4',
		},
		propsSchema: [
			{
				name: 'caption',
				label: 'Table Title',
				type: 'string',
				default: 'Users Directory',
			},
			{
				name: 'loading',
				label: 'Loading State',
				type: 'boolean',
				default: false,
			},
			{
				name: 'sticky',
				label: 'Sticky Header',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'table',
			},
		],
	},
	{
		type: 'timeline',
		name: 'UTimeline',
		category: 'data',
		icon: 'lucide:git-commit',
		description: 'Vertical chronological sequence of events, steps or activity log',
		isContainer: false,
		defaultProps: {
			items: 'Account Created:2026-01-01:User registered, Project Deployed:2026-01-15:v1.0.0 released, First Customer:2026-02-01:Paid subscription active',
			orientation: 'vertical',
			color: 'primary',
			size: 'md',
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
			margin: 'my-4',
		},
		propsSchema: [
			{
				name: 'items',
				label: 'Events (Title:Date:Description comma separated)',
				type: 'textarea',
				default: 'Account Created:2026-01-01:User registered, Project Deployed:2026-01-15:v1.0.0 released, First Customer:2026-02-01:Paid subscription active',
			},
			{
				name: 'orientation',
				label: 'Orientation',
				type: 'select',
				options: ['vertical', 'horizontal'],
				default: 'vertical',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'secondary', 'success', 'info', 'warning', 'error', 'neutral'],
				default: 'primary',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['sm', 'md', 'lg'],
				default: 'md',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'tree',
		name: 'UTree',
		category: 'data',
		icon: 'lucide:folder-tree',
		description: 'Hierarchical file or category tree view navigator',
		isContainer: false,
		defaultProps: {
			items: 'app:Folder:1, components:Folder:2, pages:Folder:3, package.json:File:4',
			color: 'primary',
			size: 'md',
			multiple: false,
			disabled: false,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
			margin: 'my-3',
		},
		propsSchema: [
			{
				name: 'items',
				label: 'Tree Nodes (Name:Type:Id comma separated)',
				type: 'textarea',
				default: 'app:Folder:1, components:Folder:2, pages:Folder:3, package.json:File:4',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'multiple',
				label: 'Multi-Select',
				type: 'boolean',
				default: false,
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'user',
		name: 'UUser',
		category: 'data',
		icon: 'lucide:user',
		description: 'User card item with avatar, display name and sub-description',
		isContainer: false,
		defaultProps: {
			name: 'Daniel Roe',
			description: 'Lead Framework Architect',
			avatar: 'https://github.com/danielroe.png',
			to: 'https://github.com/danielroe',
			target: '_blank',
			size: 'md',
			chip: false,
			as: 'div',
		},
		defaultStyles: {
			margin: 'my-2',
		},
		propsSchema: [
			{
				name: 'name',
				label: 'User Name',
				type: 'string',
				default: 'Daniel Roe',
			},
			{
				name: 'description',
				label: 'Role / Bio Text',
				type: 'string',
				default: 'Lead Framework Architect',
			},
			{
				name: 'avatar',
				label: 'Avatar URL',
				type: 'string',
				default: 'https://github.com/danielroe.png',
			},
			{
				name: 'to',
				label: 'Link Target (to)',
				type: 'string',
				default: 'https://github.com/danielroe',
			},
			{
				name: 'target',
				label: 'Target Window',
				type: 'select',
				options: ['_blank', '_self'],
				default: '_blank',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['3xs', '2xs', 'xs', 'sm', 'md', 'lg', 'xl', '2xl', '3xl'],
				default: 'md',
			},
			{
				name: 'chip',
				label: 'Online Status Chip',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
]
