import type { ComponentDefinition } from '~/types/builder'

export const elementComponents: ComponentDefinition[] = [
	{
		type: 'button',
		name: 'UButton',
		category: 'element',
		icon: 'lucide:mouse-pointer-click',
		description: 'Interactive button with multiple styles, colors, sizes and icons',
		isContainer: false,
		defaultProps: {
			label: 'Button',
			color: 'primary',
			variant: 'solid',
			size: 'md',
			icon: '',
			trailing: false,
			block: false,
			loading: false,
			disabled: false,
			to: '',
			as: 'button',
		},
		defaultStyles: {},
		propsSchema: [
			{
				name: 'label',
				label: 'Button Label',
				type: 'string',
				default: 'Button',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'secondary', 'success', 'info', 'warning', 'error', 'neutral'],
				default: 'primary',
			},
			{
				name: 'variant',
				label: 'Variant',
				type: 'select',
				options: ['solid', 'outline', 'soft', 'subtle', 'ghost', 'link'],
				default: 'solid',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'icon',
				label: 'Icon (Leading)',
				type: 'icon',
				default: '',
			},
			{
				name: 'trailing',
				label: 'Icon on Right (Trailing)',
				type: 'boolean',
				default: false,
			},
			{
				name: 'block',
				label: 'Full Width (Block)',
				type: 'boolean',
				default: false,
			},
			{
				name: 'loading',
				label: 'Loading State',
				type: 'boolean',
				default: false,
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'to',
				label: 'Link Target (to)',
				type: 'string',
				default: '',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'button',
			},
		],
	},
	{
		type: 'badge',
		name: 'UBadge',
		category: 'element',
		icon: 'lucide:award',
		description: 'Small status indicator badge label',
		isContainer: false,
		defaultProps: {
			label: 'Badge',
			color: 'primary',
			variant: 'subtle',
			size: 'md',
			square: false,
			icon: '',
			trailing: false,
			as: 'span',
		},
		defaultStyles: {},
		propsSchema: [
			{
				name: 'label',
				label: 'Label',
				type: 'string',
				default: 'Badge',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'secondary', 'success', 'info', 'warning', 'error', 'neutral'],
				default: 'primary',
			},
			{
				name: 'variant',
				label: 'Variant',
				type: 'select',
				options: ['solid', 'outline', 'soft', 'subtle'],
				default: 'subtle',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'square',
				label: 'Square Shape',
				type: 'boolean',
				default: false,
			},
			{
				name: 'icon',
				label: 'Icon',
				type: 'icon',
				default: '',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'span',
			},
		],
	},
	{
		type: 'avatar',
		name: 'UAvatar',
		category: 'element',
		icon: 'lucide:user-circle-2',
		description: 'User profile avatar with image, initials fallback, and status chip',
		isContainer: false,
		defaultProps: {
			src: 'https://avatars.githubusercontent.com/u/739984?v=4',
			alt: 'Alexandre Rochon',
			text: 'AR',
			size: 'md',
			color: 'primary',
			chip: false,
			chipColor: 'success',
			as: 'span',
		},
		defaultStyles: {},
		propsSchema: [
			{
				name: 'src',
				label: 'Image URL',
				type: 'string',
				default: 'https://avatars.githubusercontent.com/u/739984?v=4',
			},
			{
				name: 'alt',
				label: 'Alt Text',
				type: 'string',
				default: 'Alexandre Rochon',
			},
			{
				name: 'text',
				label: 'Initials Fallback Text',
				type: 'string',
				default: 'AR',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['3xs', '2xs', 'xs', 'sm', 'md', 'lg', 'xl', '2xl', '3xl'],
				default: 'md',
			},
			{
				name: 'chip',
				label: 'Status Chip Indicator',
				type: 'boolean',
				default: false,
			},
			{
				name: 'chipColor',
				label: 'Chip Color',
				type: 'select',
				options: ['success', 'warning', 'error', 'primary', 'neutral'],
				default: 'success',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'span',
			},
		],
	},
	{
		type: 'avatar-group',
		name: 'UAvatarGroup',
		category: 'element',
		icon: 'lucide:users',
		description: 'Stacked group of multiple avatars with overflow limit count badge',
		isContainer: false,
		defaultProps: {
			size: 'md',
			max: 3,
			avatars: 'https://avatars.githubusercontent.com/u/739984?v=4, https://avatars.githubusercontent.com/u/904724?v=4, https://avatars.githubusercontent.com/u/28706372?v=4, https://avatars.githubusercontent.com/u/5116549?v=4',
			as: 'div',
		},
		defaultStyles: {},
		propsSchema: [
			{
				name: 'size',
				label: 'Avatar Size',
				type: 'select',
				options: ['3xs', '2xs', 'xs', 'sm', 'md', 'lg', 'xl', '2xl', '3xl'],
				default: 'md',
			},
			{
				name: 'max',
				label: 'Max Visible',
				type: 'number',
				default: 3,
			},
			{
				name: 'avatars',
				label: 'Avatar URLs (Comma separated)',
				type: 'textarea',
				default: 'https://avatars.githubusercontent.com/u/739984?v=4, https://avatars.githubusercontent.com/u/904724?v=4, https://avatars.githubusercontent.com/u/28706372?v=4, https://avatars.githubusercontent.com/u/5116549?v=4',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'banner',
		name: 'UBanner',
		category: 'element',
		icon: 'lucide:megaphone',
		description: 'Top page promotional or announcement banner',
		isContainer: false,
		defaultProps: {
			title: 'Nuxt UI v4 is now officially released! Check out the new features.',
			icon: 'lucide:sparkles',
			color: 'primary',
			close: true,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'title',
				label: 'Announcement Title',
				type: 'string',
				default: 'Nuxt UI v4 is now officially released! Check out the new features.',
			},
			{
				name: 'icon',
				label: 'Banner Icon',
				type: 'icon',
				default: 'lucide:sparkles',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'secondary', 'success', 'info', 'warning', 'error', 'neutral'],
				default: 'primary',
			},
			{
				name: 'close',
				label: 'Show Close Button',
				type: 'boolean',
				default: true,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'alert',
		name: 'UAlert',
		category: 'element',
		icon: 'lucide:info',
		description: 'Callout notification banner with colors, variants, and action buttons',
		isContainer: false,
		defaultProps: {
			title: 'Heads up!',
			description: 'You can customize components directly in your design canvas.',
			icon: 'lucide:info',
			color: 'primary',
			variant: 'subtle',
			orientation: 'horizontal',
			close: false,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'title',
				label: 'Alert Title',
				type: 'string',
				default: 'Heads up!',
			},
			{
				name: 'description',
				label: 'Description Text',
				type: 'textarea',
				default: 'You can customize components directly in your design canvas.',
			},
			{
				name: 'icon',
				label: 'Leading Icon',
				type: 'icon',
				default: 'lucide:info',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'secondary', 'success', 'info', 'warning', 'error', 'neutral'],
				default: 'primary',
			},
			{
				name: 'variant',
				label: 'Variant',
				type: 'select',
				options: ['solid', 'outline', 'soft', 'subtle'],
				default: 'subtle',
			},
			{
				name: 'orientation',
				label: 'Orientation',
				type: 'select',
				options: ['horizontal', 'vertical'],
				default: 'horizontal',
			},
			{
				name: 'close',
				label: 'Show Close Button',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'calendar',
		name: 'UCalendar',
		category: 'element',
		icon: 'lucide:calendar',
		description: 'Interactive calendar date selection component',
		isContainer: false,
		defaultProps: {
			color: 'primary',
			size: 'md',
			as: 'div',
		},
		defaultStyles: {},
		propsSchema: [
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'secondary', 'success', 'info', 'warning', 'error', 'neutral'],
				default: 'primary',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['sm', 'md', 'lg'],
				default: 'md',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'chip',
		name: 'UChip',
		category: 'element',
		icon: 'lucide:bell-dot',
		description: 'Notification badge wrapper indicator',
		isContainer: true,
		defaultProps: {
			text: '9',
			color: 'error',
			size: 'md',
			position: 'top-right',
			inset: false,
			as: 'div',
		},
		defaultStyles: {},
		propsSchema: [
			{
				name: 'text',
				label: 'Chip Text/Number',
				type: 'string',
				default: '9',
			},
			{
				name: 'color',
				label: 'Chip Color',
				type: 'select',
				options: ['error', 'primary', 'secondary', 'success', 'warning', 'neutral'],
				default: 'error',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['3xs', '2xs', 'xs', 'sm', 'md', 'lg', 'xl', '2xl', '3xl'],
				default: 'md',
			},
			{
				name: 'position',
				label: 'Position',
				type: 'select',
				options: ['top-right', 'top-left', 'bottom-right', 'bottom-left'],
				default: 'top-right',
			},
			{
				name: 'inset',
				label: 'Inset',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'collapsible',
		name: 'UCollapsible',
		category: 'element',
		icon: 'lucide:chevrons-up-down',
		description: 'Expand and collapse content with smooth animation',
		isContainer: true,
		defaultProps: {
			title: 'Toggle Section',
			open: false,
			disabled: false,
			as: 'div',
		},
		defaultStyles: {
			margin: 'my-3',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'title',
				label: 'Header Title',
				type: 'string',
				default: 'Toggle Section',
			},
			{
				name: 'open',
				label: 'Initially Open',
				type: 'boolean',
				default: false,
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'field-group',
		name: 'UFieldGroup',
		category: 'element',
		icon: 'lucide:group',
		description: 'Group form elements or buttons horizontally or vertically',
		isContainer: true,
		defaultProps: {
			size: 'md',
			orientation: 'horizontal',
			as: 'div',
		},
		defaultStyles: {
			margin: 'my-3',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'orientation',
				label: 'Orientation',
				type: 'select',
				options: ['horizontal', 'vertical'],
				default: 'horizontal',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'icon',
		name: 'UIcon',
		category: 'element',
		icon: 'lucide:shapes',
		description: 'Standalone Icon with customizable size and color',
		isContainer: false,
		defaultProps: {
			name: 'lucide:sparkles',
			size: 'h-8 w-8',
			color: 'text-primary',
			as: 'span',
		},
		defaultStyles: {},
		propsSchema: [
			{
				name: 'name',
				label: 'Icon Identifier',
				type: 'icon',
				default: 'lucide:sparkles',
			},
			{
				name: 'size',
				label: 'Icon Size',
				type: 'select',
				options: ['h-4 w-4', 'h-5 w-5', 'h-6 w-6', 'h-8 w-8', 'h-10 w-10', 'h-12 w-12'],
				default: 'h-8 w-8',
			},
			{
				name: 'color',
				label: 'Icon Color',
				type: 'select',
				options: ['text-primary', 'text-neutral-500', 'text-success-500', 'text-warning-500', 'text-error-500', 'text-neutral-900 dark:text-white'],
				default: 'text-primary',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'span',
			},
		],
	},
	{
		type: 'kbd',
		name: 'UKbd',
		category: 'element',
		icon: 'lucide:keyboard',
		description: 'A badge to display keyboard shortcuts',
		isContainer: false,
		defaultProps: {
			value: '⌘K',
			size: 'md',
			variant: 'outline',
			as: 'kbd',
		},
		defaultStyles: {},
		propsSchema: [
			{
				name: 'value',
				label: 'Key Value',
				type: 'string',
				default: '⌘K',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['sm', 'md', 'lg'],
				default: 'md',
			},
			{
				name: 'variant',
				label: 'Variant',
				type: 'select',
				options: ['outline', 'subtle', 'solid'],
				default: 'outline',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'kbd',
			},
		],
	},
	{
		type: 'progress',
		name: 'UProgress',
		category: 'element',
		icon: 'lucide:loader',
		description: 'Progress bar with status value or indeterminate mode',
		isContainer: false,
		defaultProps: {
			value: 75,
			max: 100,
			color: 'primary',
			size: 'md',
			status: true,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'value',
				label: 'Progress Value',
				type: 'number',
				default: 75,
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'secondary', 'success', 'info', 'warning', 'error', 'neutral'],
				default: 'primary',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'status',
				label: 'Show Percentage Text',
				type: 'boolean',
				default: true,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'progress-group',
		name: 'UProgressGroup',
		category: 'element',
		icon: 'lucide:layers-2',
		description: 'Multi-bar grouped progress indicators',
		isContainer: false,
		defaultProps: {
			items: 'Design:85, Development:60, Testing:40',
			color: 'primary',
			size: 'md',
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
			margin: 'my-3',
		},
		propsSchema: [
			{
				name: 'items',
				label: 'Items (Label:Percentage comma separated)',
				type: 'textarea',
				default: 'Design:85, Development:60, Testing:40',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'secondary', 'success', 'info', 'warning', 'error', 'neutral'],
				default: 'primary',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'skeleton',
		name: 'USkeleton',
		category: 'element',
		icon: 'lucide:scan',
		description: 'Placeholder loading skeleton animation shape',
		isContainer: false,
		defaultProps: {
			shape: 'rectangle',
			height: 'h-6',
			width: 'w-full',
			as: 'div',
		},
		defaultStyles: {
			margin: 'my-2',
		},
		propsSchema: [
			{
				name: 'shape',
				label: 'Shape',
				type: 'select',
				options: ['rectangle', 'circle', 'card', 'avatar-text'],
				default: 'rectangle',
			},
			{
				name: 'height',
				label: 'Height',
				type: 'select',
				options: ['h-4', 'h-6', 'h-8', 'h-12', 'h-24', 'h-36'],
				default: 'h-6',
			},
			{
				name: 'width',
				label: 'Width',
				type: 'select',
				options: ['w-1/4', 'w-1/2', 'w-3/4', 'w-full', 'w-12'],
				default: 'w-full',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'card',
		name: 'UCard',
		category: 'element',
		icon: 'lucide:panel-top',
		description: 'Display content in a card with a header, title, description, body and footer',
		isContainer: true,
		defaultProps: {
			title: 'Card Title',
			description: 'Card description providing additional context.',
			variant: 'outline',
			as: 'div',
			showHeader: false,
			headerText: '',
			showFooter: false,
			footerText: '',
		},
		defaultStyles: {
			padding: 'p-0',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'title',
				label: 'Card Title (prop)',
				type: 'string',
				default: 'Card Title',
			},
			{
				name: 'description',
				label: 'Card Description (prop)',
				type: 'textarea',
				default: 'Card description providing additional context.',
			},
			{
				name: 'variant',
				label: 'Variant',
				type: 'select',
				options: ['outline', 'soft', 'subtle', 'solid'],
				default: 'outline',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
			{
				name: 'showHeader',
				label: 'Custom Header Slot',
				type: 'boolean',
				default: false,
			},
			{
				name: 'headerText',
				label: 'Header Text',
				type: 'string',
				default: '',
			},
			{
				name: 'showFooter',
				label: 'Show Footer Slot',
				type: 'boolean',
				default: false,
			},
			{
				name: 'footerText',
				label: 'Footer Text',
				type: 'string',
				default: '',
			},
		],
	},
	{
		type: 'separator',
		name: 'USeparator',
		category: 'element',
		icon: 'lucide:minus',
		description: 'Visual divider with optional label or icon',
		isContainer: false,
		defaultProps: {
			label: '',
			icon: '',
			color: 'neutral',
			type: 'solid',
			orientation: 'horizontal',
			as: 'hr',
		},
		defaultStyles: {
			margin: 'my-4',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'label',
				label: 'Center Label',
				type: 'string',
				default: '',
			},
			{
				name: 'icon',
				label: 'Center Icon',
				type: 'icon',
				default: '',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['neutral', 'primary', 'secondary', 'success', 'warning', 'error'],
				default: 'neutral',
			},
			{
				name: 'type',
				label: 'Style Type',
				type: 'select',
				options: ['solid', 'dashed', 'dotted'],
				default: 'solid',
			},
			{
				name: 'orientation',
				label: 'Orientation',
				type: 'select',
				options: ['horizontal', 'vertical'],
				default: 'horizontal',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'hr',
			},
		],
	},
]
