import type { ComponentDefinition } from '~/types/builder'

export const formComponents: ComponentDefinition[] = [
	{
		type: 'form',
		name: 'UForm',
		category: 'form',
		icon: 'lucide:file-input',
		description: 'Form container wrapper with validation and submit handler',
		isContainer: true,
		defaultProps: {
			title: 'User Profile Form',
			submitText: 'Save Changes',
			as: 'form',
		},
		defaultStyles: {
			width: 'w-full',
			margin: 'my-4',
		},
		propsSchema: [
			{
				name: 'title',
				label: 'Form Title',
				type: 'string',
				default: 'User Profile Form',
			},
			{
				name: 'submitText',
				label: 'Submit Button Text',
				type: 'string',
				default: 'Save Changes',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'form',
			},
		],
	},
	{
		type: 'form-field',
		name: 'UFormField',
		category: 'form',
		icon: 'lucide:form-input',
		description: 'Form field container with label, description, help and error message',
		isContainer: true,
		defaultProps: {
			label: 'Email Address',
			description: 'We will never share your email with third parties.',
			help: '',
			required: true,
			error: '',
			size: 'md',
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
			margin: 'my-3',
		},
		propsSchema: [
			{
				name: 'label',
				label: 'Field Label',
				type: 'string',
				default: 'Email Address',
			},
			{
				name: 'description',
				label: 'Help Description',
				type: 'string',
				default: 'We will never share your email with third parties.',
			},
			{
				name: 'help',
				label: 'Help Text (Bottom)',
				type: 'string',
				default: '',
			},
			{
				name: 'required',
				label: 'Required Indicator',
				type: 'boolean',
				default: true,
			},
			{
				name: 'error',
				label: 'Error Message',
				type: 'string',
				default: '',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'input',
		name: 'UInput',
		category: 'form',
		icon: 'lucide:text-cursor-input',
		description: 'Text input field with icons, sizes and states',
		isContainer: false,
		defaultProps: {
			placeholder: 'Enter your email...',
			icon: 'lucide:mail',
			color: 'primary',
			variant: 'outline',
			size: 'md',
			type: 'text',
			disabled: false,
			loading: false,
			as: 'input',
		},
		defaultStyles: {
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'placeholder',
				label: 'Placeholder',
				type: 'string',
				default: 'Enter your email...',
			},
			{
				name: 'icon',
				label: 'Leading Icon',
				type: 'icon',
				default: 'lucide:mail',
			},
			{
				name: 'type',
				label: 'Input Type',
				type: 'select',
				options: ['text', 'email', 'password', 'url', 'tel', 'search'],
				default: 'text',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'variant',
				label: 'Variant',
				type: 'select',
				options: ['outline', 'soft', 'subtle', 'ghost', 'none'],
				default: 'outline',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'loading',
				label: 'Loading State',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'input',
			},
		],
	},
	{
		type: 'input-number',
		name: 'UInputNumber',
		category: 'form',
		icon: 'lucide:binary',
		description: 'Numeric step counter input with up/down controls',
		isContainer: false,
		defaultProps: {
			value: 1,
			min: 0,
			max: 100,
			step: 1,
			color: 'primary',
			size: 'md',
			disabled: false,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'value',
				label: 'Initial Value',
				type: 'number',
				default: 1,
			},
			{
				name: 'min',
				label: 'Minimum',
				type: 'number',
				default: 0,
			},
			{
				name: 'max',
				label: 'Maximum',
				type: 'number',
				default: 100,
			},
			{
				name: 'step',
				label: 'Step Increment',
				type: 'number',
				default: 1,
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'input-date',
		name: 'UInputDate',
		category: 'form',
		icon: 'lucide:calendar-days',
		description: 'Date picker input dropdown field',
		isContainer: false,
		defaultProps: {
			placeholder: 'Select a date...',
			icon: 'lucide:calendar',
			color: 'primary',
			size: 'md',
			disabled: false,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'placeholder',
				label: 'Placeholder',
				type: 'string',
				default: 'Select a date...',
			},
			{
				name: 'icon',
				label: 'Icon',
				type: 'icon',
				default: 'lucide:calendar',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'input-time',
		name: 'UInputTime',
		category: 'form',
		icon: 'lucide:clock',
		description: 'Time selection input field',
		isContainer: false,
		defaultProps: {
			placeholder: 'Select time...',
			icon: 'lucide:clock',
			color: 'primary',
			size: 'md',
			disabled: false,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'placeholder',
				label: 'Placeholder',
				type: 'string',
				default: 'Select time...',
			},
			{
				name: 'icon',
				label: 'Icon',
				type: 'icon',
				default: 'lucide:clock',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'input-menu',
		name: 'UInputMenu',
		category: 'form',
		icon: 'lucide:list-filter',
		description: 'Autocomplete dropdown menu input',
		isContainer: false,
		defaultProps: {
			placeholder: 'Search frameworks...',
			items: 'Nuxt, Vue, Next, React, Svelte, Astro',
			color: 'primary',
			size: 'md',
			disabled: false,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'placeholder',
				label: 'Placeholder',
				type: 'string',
				default: 'Search frameworks...',
			},
			{
				name: 'items',
				label: 'Options (Comma separated)',
				type: 'textarea',
				default: 'Nuxt, Vue, Next, React, Svelte, Astro',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'input-tags',
		name: 'UInputTags',
		category: 'form',
		icon: 'lucide:tags',
		description: 'Multi-tag pill badge creator input',
		isContainer: false,
		defaultProps: {
			placeholder: 'Add tags...',
			tags: 'Vue 3, Nuxt 4, Tailwind CSS, TypeScript',
			color: 'primary',
			size: 'md',
			disabled: false,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'placeholder',
				label: 'Placeholder',
				type: 'string',
				default: 'Add tags...',
			},
			{
				name: 'tags',
				label: 'Initial Tags (Comma separated)',
				type: 'textarea',
				default: 'Vue 3, Nuxt 4, Tailwind CSS, TypeScript',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'input-rating',
		name: 'UInputRating',
		category: 'form',
		icon: 'lucide:star',
		description: 'Star score rating input control',
		isContainer: false,
		defaultProps: {
			value: 4,
			max: 5,
			color: 'warning',
			size: 'md',
			disabled: false,
			as: 'div',
		},
		defaultStyles: {},
		propsSchema: [
			{
				name: 'value',
				label: 'Rating Value',
				type: 'number',
				default: 4,
			},
			{
				name: 'max',
				label: 'Maximum Stars',
				type: 'number',
				default: 5,
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['warning', 'primary', 'neutral', 'success', 'error'],
				default: 'warning',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'pin-input',
		name: 'UPinInput',
		category: 'form',
		icon: 'lucide:key-round',
		description: 'OTP / Security PIN digit input boxes',
		isContainer: false,
		defaultProps: {
			length: 4,
			placeholder: '○',
			color: 'primary',
			size: 'md',
			type: 'text',
			disabled: false,
			as: 'div',
		},
		defaultStyles: {
			margin: 'my-3',
		},
		propsSchema: [
			{
				name: 'length',
				label: 'Number of Digits',
				type: 'number',
				default: 4,
			},
			{
				name: 'placeholder',
				label: 'Placeholder Char',
				type: 'string',
				default: '○',
			},
			{
				name: 'type',
				label: 'Input Type',
				type: 'select',
				options: ['text', 'number'],
				default: 'text',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'color-picker',
		name: 'UColorPicker',
		category: 'form',
		icon: 'lucide:palette',
		description: 'Hex / RGBA color palette picker',
		isContainer: false,
		defaultProps: {
			defaultValue: '#00C16A',
			format: 'hex',
			size: 'md',
			disabled: false,
			as: 'div',
		},
		defaultStyles: {
			margin: 'my-2',
		},
		propsSchema: [
			{
				name: 'defaultValue',
				label: 'Default Color',
				type: 'color',
				default: '#00C16A',
			},
			{
				name: 'format',
				label: 'Color Format',
				type: 'select',
				options: ['hex', 'rgb', 'hsl', 'cmyk', 'lab'],
				default: 'hex',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'file-upload',
		name: 'UFileUpload',
		category: 'form',
		icon: 'lucide:upload-cloud',
		description: 'Drag & Drop file upload dropzone',
		isContainer: false,
		defaultProps: {
			label: 'Click or drag files here to upload',
			hint: 'PNG, JPG, PDF up to 10MB',
			icon: 'lucide:upload-cloud',
			multiple: true,
			disabled: false,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
			margin: 'my-3',
		},
		propsSchema: [
			{
				name: 'label',
				label: 'Dropzone Label',
				type: 'string',
				default: 'Click or drag files here to upload',
			},
			{
				name: 'hint',
				label: 'Supported file types hint',
				type: 'string',
				default: 'PNG, JPG, PDF up to 10MB',
			},
			{
				name: 'icon',
				label: 'Dropzone Icon',
				type: 'icon',
				default: 'lucide:upload-cloud',
			},
			{
				name: 'multiple',
				label: 'Allow Multiple',
				type: 'boolean',
				default: true,
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'textarea',
		name: 'UTextarea',
		category: 'form',
		icon: 'lucide:file-text',
		description: 'Multi-line text area input',
		isContainer: false,
		defaultProps: {
			placeholder: 'Write your message...',
			rows: 4,
			color: 'primary',
			variant: 'outline',
			size: 'md',
			disabled: false,
			autoresize: false,
			as: 'textarea',
		},
		defaultStyles: {
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'placeholder',
				label: 'Placeholder',
				type: 'string',
				default: 'Write your message...',
			},
			{
				name: 'rows',
				label: 'Rows',
				type: 'number',
				default: 4,
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'variant',
				label: 'Variant',
				type: 'select',
				options: ['outline', 'soft', 'subtle', 'none'],
				default: 'outline',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'autoresize',
				label: 'Auto Resize',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'textarea',
			},
		],
	},
	{
		type: 'select',
		name: 'USelect',
		category: 'form',
		icon: 'lucide:chevron-down-square',
		description: 'Standard native dropdown selection select',
		isContainer: false,
		defaultProps: {
			placeholder: 'Select a country...',
			options: 'United States, Indonesia, United Kingdom, Japan, Germany',
			color: 'primary',
			variant: 'outline',
			size: 'md',
			disabled: false,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'placeholder',
				label: 'Placeholder',
				type: 'string',
				default: 'Select a country...',
			},
			{
				name: 'options',
				label: 'Options (Comma separated)',
				type: 'textarea',
				default: 'United States, Indonesia, United Kingdom, Japan, Germany',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'variant',
				label: 'Variant',
				type: 'select',
				options: ['outline', 'soft', 'subtle', 'ghost', 'none'],
				default: 'outline',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'select-menu',
		name: 'USelectMenu',
		category: 'form',
		icon: 'lucide:chevrons-up-down',
		description: 'Custom rich select dropdown with search and avatars',
		isContainer: false,
		defaultProps: {
			placeholder: 'Select team member...',
			items: 'Alexandre Rochon, Sébastien Chopin, Anthony Fu, Benjamin Canac',
			searchable: true,
			color: 'primary',
			variant: 'outline',
			size: 'md',
			disabled: false,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'placeholder',
				label: 'Placeholder',
				type: 'string',
				default: 'Select team member...',
			},
			{
				name: 'items',
				label: 'Items (Comma separated)',
				type: 'textarea',
				default: 'Alexandre Rochon, Sébastien Chopin, Anthony Fu, Benjamin Canac',
			},
			{
				name: 'searchable',
				label: 'Searchable Filter',
				type: 'boolean',
				default: true,
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'variant',
				label: 'Variant',
				type: 'select',
				options: ['outline', 'soft', 'subtle', 'ghost', 'none'],
				default: 'outline',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'listbox',
		name: 'UListbox',
		category: 'form',
		icon: 'lucide:check-check',
		description: 'Accessible listbox option picker',
		isContainer: false,
		defaultProps: {
			placeholder: 'Choose role...',
			items: 'Administrator, Editor, Contributor, Viewer',
			color: 'primary',
			size: 'md',
			disabled: false,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'placeholder',
				label: 'Placeholder',
				type: 'string',
				default: 'Choose role...',
			},
			{
				name: 'items',
				label: 'Items (Comma separated)',
				type: 'textarea',
				default: 'Administrator, Editor, Contributor, Viewer',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'radio-group',
		name: 'URadioGroup',
		category: 'form',
		icon: 'lucide:circle-dot',
		description: 'Radio button choice group',
		isContainer: false,
		defaultProps: {
			legend: 'Select a plan',
			items: 'Startup ($19/mo), Business ($49/mo), Enterprise ($99/mo)',
			orientation: 'vertical',
			color: 'primary',
			variant: 'list',
			size: 'md',
			disabled: false,
			as: 'div',
		},
		defaultStyles: {
			margin: 'my-3',
		},
		propsSchema: [
			{
				name: 'legend',
				label: 'Group Legend',
				type: 'string',
				default: 'Select a plan',
			},
			{
				name: 'items',
				label: 'Items (Comma separated)',
				type: 'textarea',
				default: 'Startup ($19/mo), Business ($49/mo), Enterprise ($99/mo)',
			},
			{
				name: 'orientation',
				label: 'Orientation',
				type: 'select',
				options: ['vertical', 'horizontal'],
				default: 'vertical',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'variant',
				label: 'Variant',
				type: 'select',
				options: ['list', 'card', 'table'],
				default: 'list',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'checkbox-group',
		name: 'UCheckboxGroup',
		category: 'form',
		icon: 'lucide:list-checks',
		description: 'Group of multiple checkbox choices',
		isContainer: false,
		defaultProps: {
			legend: 'Notifications',
			items: 'Email Notifications, SMS Alerts, Weekly Summary Digest',
			orientation: 'vertical',
			color: 'primary',
			variant: 'list',
			size: 'md',
			disabled: false,
			as: 'div',
		},
		defaultStyles: {
			margin: 'my-3',
		},
		propsSchema: [
			{
				name: 'legend',
				label: 'Group Legend',
				type: 'string',
				default: 'Notifications',
			},
			{
				name: 'items',
				label: 'Items (Comma separated)',
				type: 'textarea',
				default: 'Email Notifications, SMS Alerts, Weekly Summary Digest',
			},
			{
				name: 'orientation',
				label: 'Orientation',
				type: 'select',
				options: ['vertical', 'horizontal'],
				default: 'vertical',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'variant',
				label: 'Variant',
				type: 'select',
				options: ['list', 'card', 'table'],
				default: 'list',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'switch',
		name: 'USwitch',
		category: 'form',
		icon: 'lucide:toggle-left',
		description: 'Toggle switch input for binary settings',
		isContainer: false,
		defaultProps: {
			label: 'Enable Email Notifications',
			description: 'Receive real-time updates directly to your inbox',
			color: 'primary',
			size: 'md',
			checked: true,
			disabled: false,
			loading: false,
			as: 'button',
		},
		defaultStyles: {},
		propsSchema: [
			{
				name: 'label',
				label: 'Switch Label',
				type: 'string',
				default: 'Enable Email Notifications',
			},
			{
				name: 'description',
				label: 'Helper Description',
				type: 'string',
				default: 'Receive real-time updates directly',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'checked',
				label: 'Initial State',
				type: 'boolean',
				default: true,
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'loading',
				label: 'Loading State',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'button',
			},
		],
	},
	{
		type: 'checkbox',
		name: 'UCheckbox',
		category: 'form',
		icon: 'lucide:check-square',
		description: 'Checkbox input for agreements and choices',
		isContainer: false,
		defaultProps: {
			label: 'I accept the terms and privacy policy',
			description: '',
			color: 'primary',
			variant: 'list',
			size: 'md',
			checked: true,
			disabled: false,
			required: false,
			as: 'div',
		},
		defaultStyles: {},
		propsSchema: [
			{
				name: 'label',
				label: 'Label',
				type: 'string',
				default: 'I accept the terms and privacy policy',
			},
			{
				name: 'description',
				label: 'Description',
				type: 'string',
				default: '',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'variant',
				label: 'Variant',
				type: 'select',
				options: ['list', 'card'],
				default: 'list',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'checked',
				label: 'Checked',
				type: 'boolean',
				default: true,
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'required',
				label: 'Required',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'slider',
		name: 'USlider',
		category: 'form',
		icon: 'lucide:sliders-horizontal',
		description: 'Range slider input for numeric values',
		isContainer: false,
		defaultProps: {
			min: 0,
			max: 100,
			step: 1,
			value: 65,
			color: 'primary',
			size: 'md',
			disabled: false,
			orientation: 'horizontal',
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'value',
				label: 'Initial Value',
				type: 'number',
				default: 65,
			},
			{
				name: 'min',
				label: 'Minimum Value',
				type: 'number',
				default: 0,
			},
			{
				name: 'max',
				label: 'Maximum Value',
				type: 'number',
				default: 100,
			},
			{
				name: 'step',
				label: 'Step',
				type: 'number',
				default: 1,
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'orientation',
				label: 'Orientation',
				type: 'select',
				options: ['horizontal', 'vertical'],
				default: 'horizontal',
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
]
