import type { ComponentDefinition } from '~/types/builder'

export const layoutComponents: ComponentDefinition[] = [
	{
		type: 'app',
		name: 'UApp',
		category: 'layout',
		icon: 'lucide:monitor',
		description: 'Root container wrapper for Nuxt UI applications with toast and modal providers',
		isContainer: true,
		defaultProps: {
			toaster: true,
			as: 'div',
		},
		defaultStyles: {
			padding: 'p-0',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'toaster',
				label: 'Enable Toaster Provider',
				type: 'boolean',
				default: true,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'container',
		name: 'UContainer',
		category: 'layout',
		icon: 'lucide:box-select',
		description: 'Responsive centered content container with max-width limits',
		isContainer: true,
		defaultProps: {
			as: 'div',
		},
		defaultStyles: {
			padding: 'p-6',
			maxWidth: 'max-w-7xl',
			margin: 'mx-auto',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'error',
		name: 'UError',
		category: 'layout',
		icon: 'lucide:alert-octagon',
		description: 'Error layout page display with status code, message and action',
		isContainer: false,
		defaultProps: {
			statusCode: 404,
			statusMessage: 'Page not found',
			message: 'The page you are looking for does not exist or has been moved.',
			as: 'div',
		},
		defaultStyles: {
			padding: 'p-8',
			width: 'w-full',
			margin: 'my-6',
		},
		propsSchema: [
			{
				name: 'statusCode',
				label: 'Status Code',
				type: 'number',
				default: 404,
			},
			{
				name: 'statusMessage',
				label: 'Status Message',
				type: 'string',
				default: 'Page not found',
			},
			{
				name: 'message',
				label: 'Description',
				type: 'textarea',
				default: 'The page you are looking for does not exist or has been moved.',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'header',
		name: 'UHeader',
		category: 'layout',
		icon: 'lucide:panel-top-close',
		description: 'Top global navigation bar with slots for logo, navigation links, actions, and mobile drawer toggle',
		isContainer: true,
		defaultProps: {
			title: 'Nuxt UI',
			to: '/',
			mode: 'modal',
			toggle: true,
			toggleSide: 'right',
			autoClose: true,
			as: 'header',
		},
		defaultStyles: {
			padding: 'p-0',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'title',
				label: 'Header Title',
				type: 'string',
				default: 'Nuxt UI',
			},
			{
				name: 'to',
				label: 'Title Link (to)',
				type: 'string',
				default: '/',
			},
			{
				name: 'mode',
				label: 'Menu Mode',
				type: 'select',
				options: ['modal', 'drawer', 'slideover'],
				default: 'modal',
			},
			{
				name: 'toggle',
				label: 'Show Mobile Toggle',
				type: 'boolean',
				default: true,
			},
			{
				name: 'toggleSide',
				label: 'Toggle Button Side',
				type: 'select',
				options: ['right', 'left'],
				default: 'right',
			},
			{
				name: 'autoClose',
				label: 'Auto Close On Route',
				type: 'boolean',
				default: true,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'header',
			},
		],
	},
	{
		type: 'main',
		name: 'UMain',
		category: 'layout',
		icon: 'lucide:layout',
		description: 'Primary content wrapper container between header and footer',
		isContainer: true,
		defaultProps: {
			as: 'main',
		},
		defaultStyles: {
			padding: 'p-6',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'main',
			},
		],
	},
	{
		type: 'sidebar',
		name: 'USidebar',
		category: 'layout',
		icon: 'lucide:panel-left',
		description: 'Sidebar navigation panel with collapsible mode and drawer support',
		isContainer: true,
		defaultProps: {
			side: 'left',
			collapsible: true,
			as: 'aside',
		},
		defaultStyles: {
			padding: 'p-4',
			width: 'w-64',
		},
		propsSchema: [
			{
				name: 'side',
				label: 'Sidebar Position',
				type: 'select',
				options: ['left', 'right'],
				default: 'left',
			},
			{
				name: 'collapsible',
				label: 'Collapsible',
				type: 'boolean',
				default: true,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'aside',
			},
		],
	},
	{
		type: 'splitter',
		name: 'USplitter',
		category: 'layout',
		icon: 'lucide:columns-2',
		description: 'Resizable split pane layout divider container',
		isContainer: true,
		defaultProps: {
			orientation: 'horizontal',
			defaultSize: 50,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
			height: 'h-64',
		},
		propsSchema: [
			{
				name: 'orientation',
				label: 'Orientation',
				type: 'select',
				options: ['horizontal', 'vertical'],
				default: 'horizontal',
			},
			{
				name: 'defaultSize',
				label: 'Split Percentage (%)',
				type: 'number',
				default: 50,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'footer',
		name: 'UFooter',
		category: 'layout',
		icon: 'lucide:panel-bottom',
		description: 'Bottom website footer section with copyright and link slots',
		isContainer: true,
		defaultProps: {
			copyright: 'Copyright © 2026. All rights reserved.',
			as: 'footer',
		},
		defaultStyles: {
			padding: 'p-0',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'copyright',
				label: 'Copyright Notice',
				type: 'string',
				default: 'Copyright © 2026. All rights reserved.',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'footer',
			},
		],
	},
	{
		type: 'grid',
		name: 'Grid Layout',
		category: 'layout',
		icon: 'lucide:grid-2x2',
		description: 'Multi-column responsive CSS grid container',
		isContainer: true,
		defaultProps: {},
		defaultStyles: {
			display: 'grid',
			gridCols: 'grid-cols-1 md:grid-cols-2 lg:grid-cols-3',
			gap: 'gap-6',
			padding: 'p-4',
			width: 'w-full',
		},
		propsSchema: [],
	},
	{
		type: 'flex',
		name: 'Flex Box',
		category: 'layout',
		icon: 'lucide:align-horizontal-distribute-center',
		description: 'Flexible row / column layout container',
		isContainer: true,
		defaultProps: {},
		defaultStyles: {
			display: 'flex',
			flexDirection: 'row',
			justifyContent: 'between',
			alignItems: 'center',
			gap: 'gap-4',
			padding: 'p-4',
			width: 'w-full',
		},
		propsSchema: [],
	},
]
