import type { ComponentDefinition } from '~/types/builder'

export const navigationComponents: ComponentDefinition[] = [
	{
		type: 'breadcrumb',
		name: 'UBreadcrumb',
		category: 'navigation',
		icon: 'lucide:link',
		description: 'A hierarchy of links to navigate through a website',
		isContainer: false,
		defaultProps: {
			items: 'Home:/, Docs:/docs, Components:/docs/components, Breadcrumb:/docs/components/breadcrumb',
			separatorIcon: 'lucide:chevron-right',
			color: 'primary',
			as: 'nav',
		},
		defaultStyles: {
			width: 'w-full',
			margin: 'my-2',
		},
		propsSchema: [
			{
				name: 'items',
				label: 'Items (Label:Path comma separated)',
				type: 'textarea',
				default: 'Home:/, Docs:/docs, Components:/docs/components, Breadcrumb:/docs/components/breadcrumb',
			},
			{
				name: 'separatorIcon',
				label: 'Separator Icon',
				type: 'icon',
				default: 'lucide:chevron-right',
			},
			{
				name: 'color',
				label: 'Active Item Color',
				type: 'select',
				options: ['primary', 'secondary', 'success', 'info', 'warning', 'error', 'neutral'],
				default: 'primary',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'nav',
			},
		],
	},
	{
		type: 'footer-columns',
		name: 'UFooterColumns',
		category: 'navigation',
		icon: 'lucide:columns-3',
		description: 'A list of links as columns to display in your footer',
		isContainer: true,
		defaultProps: {
			columns: 'Community: Nuxters, Video Courses, GitHub | Solutions: Nuxt Content, Nuxt DevTools, Nuxt Image, Nuxt UI',
			as: 'nav',
		},
		defaultStyles: {
			width: 'w-full',
			margin: 'my-4',
		},
		propsSchema: [
			{
				name: 'columns',
				label: 'Columns & Links (Column: Link1, Link2 | Column2: Link1)',
				type: 'textarea',
				default: 'Community: Nuxters, Video Courses, GitHub | Solutions: Nuxt Content, Nuxt DevTools, Nuxt Image, Nuxt UI',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'nav',
			},
		],
	},
	{
		type: 'navigation-menu',
		name: 'UNavigationMenu',
		category: 'navigation',
		icon: 'lucide:menu',
		description: 'A list of navigation links displayed horizontally or vertically with submenus',
		isContainer: false,
		defaultProps: {
			items: 'Guide:lucide:book-open, Composables:lucide:database, Components:lucide:box, GitHub:lucide:github',
			orientation: 'horizontal',
			variant: 'pill',
			color: 'primary',
			highlight: true,
			highlightColor: 'primary',
			collapsed: false,
			trailingIcon: 'lucide:chevron-down',
			arrow: false,
			contentOrientation: 'horizontal',
			unmountOnHide: true,
			as: 'nav',
		},
		defaultStyles: {
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'items',
				label: 'Menu Items (Label:Icon comma separated)',
				type: 'textarea',
				default: 'Guide:lucide:book-open, Composables:lucide:database, Components:lucide:box, GitHub:lucide:github',
			},
			{
				name: 'orientation',
				label: 'Orientation',
				type: 'select',
				options: ['horizontal', 'vertical'],
				default: 'horizontal',
			},
			{
				name: 'variant',
				label: 'Variant',
				type: 'select',
				options: ['pill', 'link'],
				default: 'pill',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'highlight',
				label: 'Highlight Active',
				type: 'boolean',
				default: true,
			},
			{
				name: 'highlightColor',
				label: 'Highlight Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'collapsed',
				label: 'Collapsed (Vertical)',
				type: 'boolean',
				default: false,
			},
			{
				name: 'trailingIcon',
				label: 'Trailing Icon (Submenus)',
				type: 'icon',
				default: 'lucide:chevron-down',
			},
			{
				name: 'arrow',
				label: 'Show Active Indicator Arrow',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'nav',
			},
		],
	},
	{
		type: 'pagination',
		name: 'UPagination',
		category: 'navigation',
		icon: 'lucide:chevrons-left-right',
		description: 'Pagination controls to navigate through a list of split pages',
		isContainer: false,
		defaultProps: {
			page: 1,
			total: 100,
			itemsPerPage: 10,
			siblingCount: 1,
			showEdges: true,
			color: 'primary',
			variant: 'outline',
			activeColor: 'primary',
			activeVariant: 'solid',
			size: 'md',
			disabled: false,
			as: 'nav',
		},
		defaultStyles: {
			margin: 'my-3',
		},
		propsSchema: [
			{
				name: 'page',
				label: 'Current Page',
				type: 'number',
				default: 1,
			},
			{
				name: 'total',
				label: 'Total Items',
				type: 'number',
				default: 100,
			},
			{
				name: 'itemsPerPage',
				label: 'Items per Page',
				type: 'number',
				default: 10,
			},
			{
				name: 'siblingCount',
				label: 'Sibling Count',
				type: 'number',
				default: 1,
			},
			{
				name: 'showEdges',
				label: 'Show First / Last Edges',
				type: 'boolean',
				default: true,
			},
			{
				name: 'color',
				label: 'Button Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'variant',
				label: 'Button Variant',
				type: 'select',
				options: ['outline', 'soft', 'subtle', 'ghost', 'none'],
				default: 'outline',
			},
			{
				name: 'activeColor',
				label: 'Active Page Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'activeVariant',
				label: 'Active Page Variant',
				type: 'select',
				options: ['solid', 'outline', 'soft', 'subtle', 'ghost'],
				default: 'solid',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'nav',
			},
		],
	},
	{
		type: 'stepper',
		name: 'UStepper',
		category: 'navigation',
		icon: 'lucide:list-ordered',
		description: 'A multi-step workflow progress indicator and wizard controller',
		isContainer: false,
		defaultProps: {
			items: 'Account details:lucide:user:Enter your account details, Personal info:lucide:id-card:Add your personal info, Review:lucide:check-circle:Confirm and submit',
			modelValue: 1,
			orientation: 'horizontal',
			color: 'primary',
			size: 'md',
			disabled: false,
			linear: false,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
			margin: 'my-4',
		},
		propsSchema: [
			{
				name: 'items',
				label: 'Steps (Title:Icon:Description comma separated)',
				type: 'textarea',
				default: 'Account details:lucide:user:Enter your account details, Personal info:lucide:id-card:Add your personal info, Review:lucide:check-circle:Confirm and submit',
			},
			{
				name: 'modelValue',
				label: 'Current Active Step Index (1-based)',
				type: 'number',
				default: 1,
			},
			{
				name: 'orientation',
				label: 'Orientation',
				type: 'select',
				options: ['horizontal', 'vertical'],
				default: 'horizontal',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'disabled',
				label: 'Disabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'linear',
				label: 'Linear (Lock Future Steps)',
				type: 'boolean',
				default: false,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'tabs',
		name: 'UTabs',
		category: 'navigation',
		icon: 'lucide:folder-tree',
		description: 'A set of layered sections of content (tabs) with keyboard navigation',
		isContainer: false,
		defaultProps: {
			items: 'Account:lucide:user, Password:lucide:lock, Notifications:lucide:bell',
			orientation: 'horizontal',
			variant: 'pill',
			color: 'primary',
			size: 'md',
			content: true,
			unmountOnHide: true,
			as: 'div',
		},
		defaultStyles: {
			width: 'w-full',
			margin: 'my-3',
		},
		propsSchema: [
			{
				name: 'items',
				label: 'Tab Items (Label:Icon comma separated)',
				type: 'textarea',
				default: 'Account:lucide:user, Password:lucide:lock, Notifications:lucide:bell',
			},
			{
				name: 'orientation',
				label: 'Orientation',
				type: 'select',
				options: ['horizontal', 'vertical'],
				default: 'horizontal',
			},
			{
				name: 'variant',
				label: 'Variant',
				type: 'select',
				options: ['pill', 'link'],
				default: 'pill',
			},
			{
				name: 'color',
				label: 'Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'size',
				label: 'Size',
				type: 'select',
				options: ['xs', 'sm', 'md', 'lg', 'xl'],
				default: 'md',
			},
			{
				name: 'content',
				label: 'Render Default Content Area',
				type: 'boolean',
				default: true,
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
]
