import type { ComponentDefinition } from '~/types/builder'

export const pageComponents: ComponentDefinition[] = [
	{
		type: 'page-hero',
		name: 'UPageHero',
		category: 'page',
		icon: 'lucide:sparkle',
		description: 'A responsive hero for your pages with title, headline, description, links, and illustration slot',
		isContainer: true,
		defaultProps: {
			as: 'div',
			headline: 'New release',
			title: 'Ultimate Vue UI library',
			description: 'A Nuxt/Vue-integrated UI library providing a rich set of fully-styled, accessible and highly customizable components for building modern web applications.',
			orientation: 'vertical',
			reverse: false,
			primaryBtnText: 'Get started',
			primaryBtnIcon: 'lucide:square-play',
			primaryBtnColor: 'primary',
			primaryBtnVariant: 'solid',
			secondaryBtnText: 'Learn more',
			secondaryBtnIcon: 'lucide:arrow-right',
			secondaryBtnColor: 'neutral',
			secondaryBtnVariant: 'subtle',
			showIllustration: false,
			imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1000',
		},
		defaultStyles: {
			padding: 'py-20 px-6',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'headline',
				label: 'Headline / Badge',
				type: 'string',
				default: 'New release',
			},
			{
				name: 'title',
				label: 'Hero Title',
				type: 'string',
				default: 'Ultimate Vue UI library',
			},
			{
				name: 'description',
				label: 'Description',
				type: 'textarea',
				default: 'A Nuxt/Vue-integrated UI library providing a rich set of fully-styled, accessible and highly customizable components.',
			},
			{
				name: 'orientation',
				label: 'Orientation',
				type: 'select',
				options: ['vertical', 'horizontal'],
				default: 'vertical',
			},
			{
				name: 'reverse',
				label: 'Reverse Order',
				type: 'boolean',
				default: false,
			},
			{
				name: 'primaryBtnText',
				label: 'Primary Button Label',
				type: 'string',
				default: 'Get started',
			},
			{
				name: 'primaryBtnIcon',
				label: 'Primary Button Icon',
				type: 'icon',
				default: 'lucide:square-play',
			},
			{
				name: 'primaryBtnColor',
				label: 'Primary Button Color',
				type: 'select',
				options: ['primary', 'neutral', 'success', 'warning', 'error'],
				default: 'primary',
			},
			{
				name: 'primaryBtnVariant',
				label: 'Primary Button Variant',
				type: 'select',
				options: ['solid', 'outline', 'soft', 'subtle', 'ghost'],
				default: 'solid',
			},
			{
				name: 'secondaryBtnText',
				label: 'Secondary Button Label',
				type: 'string',
				default: 'Learn more',
			},
			{
				name: 'secondaryBtnIcon',
				label: 'Secondary Button Icon',
				type: 'icon',
				default: 'lucide:arrow-right',
			},
			{
				name: 'secondaryBtnColor',
				label: 'Secondary Button Color',
				type: 'select',
				options: ['neutral', 'primary', 'secondary'],
				default: 'neutral',
			},
			{
				name: 'secondaryBtnVariant',
				label: 'Secondary Button Variant',
				type: 'select',
				options: ['subtle', 'outline', 'solid', 'soft', 'ghost'],
				default: 'subtle',
			},
			{
				name: 'showIllustration',
				label: 'Show Illustration / Screenshot',
				type: 'boolean',
				default: false,
			},
			{
				name: 'imageUrl',
				label: 'Image URL',
				type: 'string',
				default: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1000',
			},
			{
				name: 'as',
				label: 'Render As',
				type: 'string',
				default: 'div',
			},
		],
	},
	{
		type: 'auth-form',
		name: 'UAuthForm',
		category: 'page',
		icon: 'lucide:log-in',
		description: 'Complete authentication login / register form with social providers and fields',
		isContainer: false,
		defaultProps: {
			title: 'Welcome back',
			description: 'Enter your credentials to access your account.',
			icon: 'lucide:lock',
			submitBtnText: 'Continue with Email',
			showProviders: true,
			showEmail: true,
			showPassword: true,
		},
		defaultStyles: {
			maxWidth: 'max-w-md',
			margin: 'mx-auto',
			padding: 'p-8',
		},
		propsSchema: [
			{
				name: 'title',
				label: 'Title',
				type: 'string',
				default: 'Welcome back',
			},
			{
				name: 'description',
				label: 'Description',
				type: 'string',
				default: 'Enter your credentials to access your account.',
			},
			{
				name: 'icon',
				label: 'Header Icon',
				type: 'icon',
				default: 'lucide:lock',
			},
			{
				name: 'submitBtnText',
				label: 'Submit Button Label',
				type: 'string',
				default: 'Continue with Email',
			},
			{
				name: 'showProviders',
				label: 'Show Social Providers',
				type: 'boolean',
				default: true,
			},
		],
	},
	{
		type: 'blog-post',
		name: 'UBlogPost',
		category: 'page',
		icon: 'lucide:newspaper',
		description: 'Blog post card with image cover, date badge, author avatar and reading time',
		isContainer: false,
		defaultProps: {
			title: 'Building Modern Full-Stack Vue Apps with Nuxt 4',
			description: 'Learn how the latest features of Nuxt 4 and Nuxt UI v4 streamline developer productivity and UI composition.',
			date: 'Feb 26, 2026',
			badge: 'Tutorial',
			image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800',
			authorName: 'Sarah Jenkins',
			authorRole: 'Core Developer',
			authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
			orientation: 'vertical',
		},
		defaultStyles: {
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'title',
				label: 'Article Title',
				type: 'string',
				default: 'Building Modern Full-Stack Vue Apps with Nuxt 4',
			},
			{
				name: 'description',
				label: 'Summary / Description',
				type: 'textarea',
				default: 'Learn how the latest features of Nuxt 4 streamline developer productivity.',
			},
			{
				name: 'date',
				label: 'Publish Date',
				type: 'string',
				default: 'Feb 26, 2026',
			},
			{
				name: 'badge',
				label: 'Category Badge',
				type: 'string',
				default: 'Tutorial',
			},
			{
				name: 'image',
				label: 'Cover Image URL',
				type: 'string',
				default: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800',
			},
			{
				name: 'authorName',
				label: 'Author Name',
				type: 'string',
				default: 'Sarah Jenkins',
			},
			{
				name: 'authorRole',
				label: 'Author Role',
				type: 'string',
				default: 'Core Developer',
			},
			{
				name: 'orientation',
				label: 'Card Orientation',
				type: 'select',
				options: ['vertical', 'horizontal'],
				default: 'vertical',
			},
		],
	},
	{
		type: 'blog-posts',
		name: 'UBlogPosts',
		category: 'page',
		icon: 'lucide:library',
		description: 'Container grid or list for blog post articles',
		isContainer: true,
		defaultProps: {
			orientation: 'vertical',
		},
		defaultStyles: {
			width: 'w-full',
			padding: 'py-8',
		},
		propsSchema: [
			{
				name: 'orientation',
				label: 'Layout Orientation',
				type: 'select',
				options: ['vertical', 'horizontal'],
				default: 'vertical',
			},
		],
	},
	{
		type: 'changelog-version',
		name: 'UChangelogVersion',
		category: 'page',
		icon: 'lucide:git-commit',
		description: 'Product release version card with timeline indicator and markdown body',
		isContainer: true,
		defaultProps: {
			version: 'v4.2.0',
			date: 'February 26, 2026',
			badge: 'Latest',
			title: 'Nuxt UI v4 Studio Release & Performance Upgrades',
			description: 'Introduced visual drag and drop, code export, Theme Picker, and zero-config styling.',
		},
		defaultStyles: {
			width: 'w-full',
			padding: 'py-6',
		},
		propsSchema: [
			{
				name: 'version',
				label: 'Version Tag',
				type: 'string',
				default: 'v4.2.0',
			},
			{
				name: 'date',
				label: 'Release Date',
				type: 'string',
				default: 'February 26, 2026',
			},
			{
				name: 'badge',
				label: 'Badge Status',
				type: 'string',
				default: 'Latest',
			},
			{
				name: 'title',
				label: 'Release Title',
				type: 'string',
				default: 'Nuxt UI v4 Studio Release',
			},
			{
				name: 'description',
				label: 'Summary',
				type: 'textarea',
				default: 'Introduced visual drag and drop, code export, Theme Picker, and zero-config styling.',
			},
		],
	},
	{
		type: 'changelog-versions',
		name: 'UChangelogVersions',
		category: 'page',
		icon: 'lucide:history',
		description: 'Vertical timeline list container for product releases and changelogs',
		isContainer: true,
		defaultProps: {},
		defaultStyles: {
			width: 'w-full',
			padding: 'py-12',
		},
		propsSchema: [],
	},
	{
		type: 'page',
		name: 'UPage',
		category: 'page',
		icon: 'lucide:app-window',
		description: 'Root page container wrapping header, aside, body and footer',
		isContainer: true,
		defaultProps: {},
		defaultStyles: {
			width: 'w-full',
			padding: 'py-6 px-4',
		},
		propsSchema: [],
	},
	{
		type: 'page-header',
		name: 'UPageHeader',
		category: 'page',
		icon: 'lucide:heading-1',
		description: 'Documentation or dashboard page title header with headline, subtitle and action links',
		isContainer: false,
		defaultProps: {
			headline: 'Documentation',
			title: 'Getting Started with Nuxt UI',
			description: 'A comprehensive guide to building beautiful Vue 3 and Nuxt applications with accessible components.',
			icon: 'lucide:book-open',
			primaryBtnText: 'Quickstart',
			secondaryBtnText: 'GitHub',
		},
		defaultStyles: {
			padding: 'py-8 px-4',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'headline',
				label: 'Headline',
				type: 'string',
				default: 'Documentation',
			},
			{
				name: 'title',
				label: 'Page Title',
				type: 'string',
				default: 'Getting Started with Nuxt UI',
			},
			{
				name: 'description',
				label: 'Description',
				type: 'textarea',
				default: 'A comprehensive guide to building beautiful Vue 3 applications.',
			},
			{
				name: 'icon',
				label: 'Header Icon',
				type: 'icon',
				default: 'lucide:book-open',
			},
			{
				name: 'primaryBtnText',
				label: 'Primary Action',
				type: 'string',
				default: 'Quickstart',
			},
			{
				name: 'secondaryBtnText',
				label: 'Secondary Action',
				type: 'string',
				default: 'GitHub',
			},
		],
	},
	{
		type: 'page-body',
		name: 'UPageBody',
		category: 'page',
		icon: 'lucide:align-left',
		description: 'Main page content wrapper optimized for documentation and prose reading',
		isContainer: true,
		defaultProps: {
			prose: true,
		},
		defaultStyles: {
			width: 'w-full',
			padding: 'py-4',
		},
		propsSchema: [
			{
				name: 'prose',
				label: 'Prose Typography Styling',
				type: 'boolean',
				default: true,
			},
		],
	},
	{
		type: 'page-aside',
		name: 'UPageAside',
		category: 'page',
		icon: 'lucide:panel-left-dashed',
		description: 'Documentation side navigation sidebar panel',
		isContainer: true,
		defaultProps: {
			title: 'Navigation',
		},
		defaultStyles: {
			width: 'w-64',
			padding: 'p-4',
		},
		propsSchema: [
			{
				name: 'title',
				label: 'Aside Title',
				type: 'string',
				default: 'Navigation',
			},
		],
	},
	{
		type: 'page-anchors',
		name: 'UPageAnchors',
		category: 'page',
		icon: 'lucide:list-tree',
		description: 'Table of contents / "On this page" quick jump navigation list',
		isContainer: false,
		defaultProps: {
			title: 'On this page',
			links: 'Installation,Usage,Props,Slots,Examples',
		},
		defaultStyles: {
			width: 'w-60',
			padding: 'p-4',
		},
		propsSchema: [
			{
				name: 'title',
				label: 'Title',
				type: 'string',
				default: 'On this page',
			},
			{
				name: 'links',
				label: 'Links (comma separated)',
				type: 'textarea',
				default: 'Installation,Usage,Props,Slots,Examples',
			},
		],
	},
	{
		type: 'page-grid',
		name: 'UPageGrid',
		category: 'page',
		icon: 'lucide:layout-grid',
		description: 'Responsive multi-column card grid wrapper for page sections',
		isContainer: true,
		defaultProps: {
			columns: '3',
		},
		defaultStyles: {
			width: 'w-full',
			padding: 'py-8',
		},
		propsSchema: [
			{
				name: 'columns',
				label: 'Grid Columns',
				type: 'select',
				options: ['2', '3', '4'],
				default: '3',
			},
		],
	},
	{
		type: 'page-columns',
		name: 'UPageColumns',
		category: 'page',
		icon: 'lucide:columns-3',
		description: 'Masonry / column layout container for testimonials and cards',
		isContainer: true,
		defaultProps: {},
		defaultStyles: {
			width: 'w-full',
			padding: 'py-8',
		},
		propsSchema: [],
	},
	{
		type: 'page-card',
		name: 'UPageCard',
		category: 'page',
		icon: 'lucide:square-dashed-bottom-code',
		description: 'Versatile feature and resource card with icon, highlight gradient and link action',
		isContainer: true,
		defaultProps: {
			title: 'Customizable Theming',
			description: 'Tailor colors, fonts, radius and dark mode with real-time feedback and export.',
			icon: 'lucide:palette',
			variant: 'outline',
			highlight: true,
			orientation: 'vertical',
		},
		defaultStyles: {
			padding: 'p-6',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'title',
				label: 'Card Title',
				type: 'string',
				default: 'Customizable Theming',
			},
			{
				name: 'description',
				label: 'Description',
				type: 'textarea',
				default: 'Tailor colors, fonts, radius and dark mode with real-time feedback.',
			},
			{
				name: 'icon',
				label: 'Card Icon',
				type: 'icon',
				default: 'lucide:palette',
			},
			{
				name: 'variant',
				label: 'Variant',
				type: 'select',
				options: ['outline', 'subtle', 'soft', 'solid'],
				default: 'outline',
			},
			{
				name: 'highlight',
				label: 'Gradient Highlight Glow',
				type: 'boolean',
				default: true,
			},
			{
				name: 'orientation',
				label: 'Orientation',
				type: 'select',
				options: ['vertical', 'horizontal'],
				default: 'vertical',
			},
		],
	},
	{
		type: 'page-feature',
		name: 'UPageFeature',
		category: 'page',
		icon: 'lucide:sparkles',
		description: 'Horizontal or vertical feature item with icon badge and description',
		isContainer: false,
		defaultProps: {
			title: 'Zero Configuration',
			description: 'Instant setup with automatic Nuxt 4 module registration and TypeScript typing.',
			icon: 'lucide:zap',
			orientation: 'horizontal',
		},
		defaultStyles: {
			padding: 'p-4',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'title',
				label: 'Feature Title',
				type: 'string',
				default: 'Zero Configuration',
			},
			{
				name: 'description',
				label: 'Description',
				type: 'textarea',
				default: 'Instant setup with automatic Nuxt 4 module registration.',
			},
			{
				name: 'icon',
				label: 'Feature Icon',
				type: 'icon',
				default: 'lucide:zap',
			},
			{
				name: 'orientation',
				label: 'Orientation',
				type: 'select',
				options: ['horizontal', 'vertical'],
				default: 'horizontal',
			},
		],
	},
	{
		type: 'page-section',
		name: 'UPageSection',
		category: 'page',
		icon: 'lucide:layout-panel-top',
		description: 'Full-width responsive section with headline, title, description, links, and illustration slot',
		isContainer: true,
		defaultProps: {
			headline: 'Features',
			title: 'Everything You Need to Build Modern Vue Web Apps',
			description: 'Nuxt UI provides a comprehensive suite of accessible components, composables, and theming tools.',
			icon: 'lucide:rocket',
			orientation: 'vertical',
			reverse: false,
			primaryBtnText: 'Get Started',
			secondaryBtnText: 'Explore Components',
			showIllustration: false,
			imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1000',
		},
		defaultStyles: {
			padding: 'py-20 px-6',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'headline',
				label: 'Headline',
				type: 'string',
				default: 'Features',
			},
			{
				name: 'title',
				label: 'Section Title',
				type: 'string',
				default: 'Everything You Need to Build Modern Vue Web Apps',
			},
			{
				name: 'description',
				label: 'Description',
				type: 'textarea',
				default: 'Nuxt UI provides a comprehensive suite of accessible components.',
			},
			{
				name: 'icon',
				label: 'Leading Icon',
				type: 'icon',
				default: 'lucide:rocket',
			},
			{
				name: 'orientation',
				label: 'Orientation',
				type: 'select',
				options: ['vertical', 'horizontal'],
				default: 'vertical',
			},
			{
				name: 'reverse',
				label: 'Reverse Order',
				type: 'boolean',
				default: false,
			},
			{
				name: 'primaryBtnText',
				label: 'Primary Button',
				type: 'string',
				default: 'Get Started',
			},
			{
				name: 'secondaryBtnText',
				label: 'Secondary Button',
				type: 'string',
				default: 'Explore Components',
			},
			{
				name: 'showIllustration',
				label: 'Show Illustration / Image',
				type: 'boolean',
				default: false,
			},
			{
				name: 'imageUrl',
				label: 'Image URL',
				type: 'string',
				default: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1000',
			},
		],
	},
	{
		type: 'page-cta',
		name: 'UPageCTA',
		category: 'page',
		icon: 'lucide:megaphone',
		description: 'High-converting Call To Action section with headline, title, and action buttons',
		isContainer: true,
		defaultProps: {
			headline: 'Ready to ship?',
			title: 'Start Building Your Next Nuxt Project Today',
			description: 'Join thousands of developers creating blazing-fast web applications with Nuxt UI v4.',
			primaryBtnText: 'Get Started for Free',
			secondaryBtnText: 'Contact Sales',
			variant: 'subtle',
			orientation: 'vertical',
		},
		defaultStyles: {
			padding: 'py-16 px-6',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'headline',
				label: 'Headline',
				type: 'string',
				default: 'Ready to ship?',
			},
			{
				name: 'title',
				label: 'CTA Title',
				type: 'string',
				default: 'Start Building Your Next Nuxt Project Today',
			},
			{
				name: 'description',
				label: 'Description',
				type: 'textarea',
				default: 'Join thousands of developers creating blazing-fast web applications.',
			},
			{
				name: 'primaryBtnText',
				label: 'Primary Button',
				type: 'string',
				default: 'Get Started for Free',
			},
			{
				name: 'secondaryBtnText',
				label: 'Secondary Button',
				type: 'string',
				default: 'Contact Sales',
			},
			{
				name: 'variant',
				label: 'Visual Variant',
				type: 'select',
				options: ['subtle', 'outline', 'solid', 'naked'],
				default: 'subtle',
			},
			{
				name: 'orientation',
				label: 'Orientation',
				type: 'select',
				options: ['vertical', 'horizontal'],
				default: 'vertical',
			},
		],
	},
	{
		type: 'page-logos',
		name: 'UPageLogos',
		category: 'page',
		icon: 'lucide:gallery-horizontal',
		description: 'Social proof partner and client logo showcase section',
		isContainer: false,
		defaultProps: {
			title: 'Trusted by engineering teams and innovators worldwide',
			logos: 'Vue.js,Nuxt,Vite,TailwindCSS,TypeScript,Nitro',
		},
		defaultStyles: {
			padding: 'py-12 px-6',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'title',
				label: 'Section Heading',
				type: 'string',
				default: 'Trusted by engineering teams and innovators worldwide',
			},
			{
				name: 'logos',
				label: 'Logos / Brands (comma separated)',
				type: 'textarea',
				default: 'Vue.js,Nuxt,Vite,TailwindCSS,TypeScript,Nitro',
			},
		],
	},
	{
		type: 'page-list',
		name: 'UPageList',
		category: 'page',
		icon: 'lucide:list',
		description: 'Structured list section for resources, faq or content summaries',
		isContainer: true,
		defaultProps: {
			title: 'Frequently Asked Questions',
			description: 'Everything you need to know about Nuxt UI Studio.',
		},
		defaultStyles: {
			padding: 'py-12 px-6',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'title',
				label: 'Title',
				type: 'string',
				default: 'Frequently Asked Questions',
			},
			{
				name: 'description',
				label: 'Description',
				type: 'textarea',
				default: 'Everything you need to know about Nuxt UI Studio.',
			},
		],
	},
	{
		type: 'page-links',
		name: 'UPageLinks',
		category: 'page',
		icon: 'lucide:link-2',
		description: 'Navigation link group with icons for resources and external links',
		isContainer: false,
		defaultProps: {
			title: 'Resources',
			links: 'GitHub Repository,Nuxt UI Documentation,Discord Community,Figma UI Kit',
		},
		defaultStyles: {
			width: 'w-60',
			padding: 'p-4',
		},
		propsSchema: [
			{
				name: 'title',
				label: 'Title',
				type: 'string',
				default: 'Resources',
			},
			{
				name: 'links',
				label: 'Links (comma separated)',
				type: 'textarea',
				default: 'GitHub Repository,Nuxt UI Documentation,Discord Community,Figma UI Kit',
			},
		],
	},
	{
		type: 'pricing-plan',
		name: 'UPricingPlan',
		category: 'page',
		icon: 'lucide:credit-card',
		description: 'Official Nuxt UI Pricing Plan card with features, pricing badge and CTA',
		isContainer: false,
		defaultProps: {
			title: 'Pro Plan',
			description: 'Ideal for fast-growing startups and agencies building high-impact products.',
			price: '$29',
			billingPeriod: '/month',
			badge: 'Most Popular',
			buttonText: 'Start 14-Day Free Trial',
			highlight: true,
			features: 'Unlimited projects,Nuxt 4 code export,Nuxt Content MDC support,Priority support,Custom themes',
		},
		defaultStyles: {
			padding: 'p-8',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'title',
				label: 'Plan Title',
				type: 'string',
				default: 'Pro Plan',
			},
			{
				name: 'description',
				label: 'Plan Description',
				type: 'textarea',
				default: 'Ideal for fast-growing startups and agencies.',
			},
			{
				name: 'price',
				label: 'Price',
				type: 'string',
				default: '$29',
			},
			{
				name: 'billingPeriod',
				label: 'Billing Period',
				type: 'string',
				default: '/month',
			},
			{
				name: 'badge',
				label: 'Highlight Badge',
				type: 'string',
				default: 'Most Popular',
			},
			{
				name: 'buttonText',
				label: 'Button Label',
				type: 'string',
				default: 'Start 14-Day Free Trial',
			},
			{
				name: 'highlight',
				label: 'Highlighted / Featured',
				type: 'boolean',
				default: true,
			},
			{
				name: 'features',
				label: 'Features List (comma separated)',
				type: 'textarea',
				default: 'Unlimited projects,Nuxt 4 code export,Nuxt Content MDC support,Priority support,Custom themes',
			},
		],
	},
	{
		type: 'pricing-plans',
		name: 'UPricingPlans',
		category: 'page',
		icon: 'lucide:table-properties',
		description: 'Multi-column grid container for UPricingPlan cards',
		isContainer: true,
		defaultProps: {
			scale: true,
		},
		defaultStyles: {
			padding: 'py-16 px-6',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'scale',
				label: 'Scale Featured Plan',
				type: 'boolean',
				default: true,
			},
		],
	},
	{
		type: 'pricing-table',
		name: 'UPricingTable',
		category: 'page',
		icon: 'lucide:table',
		description: 'Feature comparison matrix table across pricing tiers',
		isContainer: false,
		defaultProps: {
			title: 'Compare All Plan Features',
			description: 'Find the plan that matches your project requirements and team scale.',
		},
		defaultStyles: {
			padding: 'py-16 px-6',
			width: 'w-full',
		},
		propsSchema: [
			{
				name: 'title',
				label: 'Table Title',
				type: 'string',
				default: 'Compare All Plan Features',
			},
			{
				name: 'description',
				label: 'Description',
				type: 'textarea',
				default: 'Find the plan that matches your project requirements.',
			},
		],
	},
]
